force-app/main/default/objects/Apex_Testing_Global_Variable__c/Apex_Testing_Global_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to store global variables during test execution</description>
    <label>Apex Testing Global Variable</label>
    <nameField>
        <label>Apex Testing Global Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Testing Global Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change_Account_Relation__c/Field_Change_Account_Relation__c.object-meta.xml
<CustomObject>
    <label>Field Change Account Relation</label>
    <nameField>
        <displayFormat>FCAR-{0000}</displayFormat>
        <label>Field Change Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Change Account Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Field Change Account Relations</relationshipLabel>
    <relationshipName>Field_Change_Account_Relations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FieldChangeTestUtility.cls
public class FieldChangeTestUtility {
    public static final Integer TESTING_ACCOUNT_FIELD_METADATA_COUNT = 2;
    public static final Integer TESTING_CONTACT_FIELD_METADATA_COUNT = 2;
    public static final Set<String> TESTING_FIELD_CHANGE_METADATA = new Set<String> {'FirstName','LastName','Name','AccountNumber'};
    public static final String EVENT_COUNT_CUSTOM_SETTING_NAME = 'Event Count';
    public static final String EVENT_UUID_CUSTOM_SETTING_NAME = 'Event Uuid';
    public static final String DEFAULT_OBJECT_NAME = 'Account';
    public static final String DEFAULT_FIELD_NAME = 'Name';
    public static final String DEFAULT_RECORD_ID_PREFIX = Account.sObjectType.getDescribe().getKeyPrefix();
    public static final String DEFAULT_RELATION_OBJECT_NAME = 'Field_Change_Account_Relation__c';
    public static final String DEFAULT_RELATION_FIELD_NAME = 'Account__c';
    public static final String DEFAULT_RELATION_ID_PREFIX = Field_Change_Account_Relation__c.sObjectType.getDescribe().getKeyPrefix();
    public static final Integer DAYS_TO_PRUNE = 10;

    public static void updateEventCallbackSuccessGlobalVariables(List<String> eventUuids) {
        List<Apex_Testing_Global_Variable__c> globalVars = TestUtility.globalVariables;
        
        if (globalVars == null) {
            globalVars = new List<Apex_Testing_Global_Variable__c> {
                new Apex_Testing_Global_Variable__c(
                    Name = EVENT_COUNT_CUSTOM_SETTING_NAME,
                    Value__c = eventUuids.size().toString()
                ),
                new Apex_Testing_Global_Variable__c(
                    Name = EVENT_UUID_CUSTOM_SETTING_NAME,
                    Value__c = eventUuids[0]
                )
            };
            TestUtility.updateGlobalVariables(globalVars);
        } else {
            Apex_Testing_Global_Variable__c eventCount, eventUuid;
            for (Apex_Testing_Global_Variable__c var : globalVars) {
                if (var.Name == EVENT_COUNT_CUSTOM_SETTING_NAME) {
                    eventCount = var;
                } else if (var.Name == EVENT_UUID_CUSTOM_SETTING_NAME) {
                    eventUuid = var;
                }
            }
            if (!eventUuids.contains(eventUuid.Value__c)) {
                eventCount.Value__c = (Integer.valueOf(eventCount.Value__c) + eventUuids.size()).toString();
                eventUuid.Value__c = eventUuids[0];
                globalVars = new List<Apex_Testing_Global_Variable__c> {eventCount, eventUuid};
                TestUtility.updateGlobalVariables(globalVars);
            }
        }
    }

    public static void updateEventCallbackFailureGlobalVariables(Integer retryCounter) {
        TestUtility.updateGlobalVariables(new List<Apex_Testing_Global_Variable__c>{
            new Apex_Testing_Global_Variable__c(
                Name = EVENT_COUNT_CUSTOM_SETTING_NAME,
                Value__c = '0'
        )});
    }
}