force-app/main/default/objects/Field_Change__c/Field_Change__c.object-meta.xml
<CustomObject>
    <label>Field Change</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Field Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change__c/fields/Date_Changed__c.field-meta.xml
<CustomField>
    <fullName>Date_Changed__c</fullName>
    <label>Date Changed</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/Field_Change_Relation_Tracking__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to store the API names of the various Field Change Tracking Relation objects</description>
    <label>Field Change Relation Tracking</label>
    <pluralLabel>Field Change Relation Tracking</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Relation_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Relation_Object_Name__c</fullName>
    <label>Relation Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FieldChangePruningBatch.cls
public class FieldChangePruningBatch implements Database.Batchable<sObject> {
    private String query;

    public FieldChangePruningBatch(Integer numOfDays) {
        query = 'SELECT Id FROM Field_Change__c WHERE Date_Changed__c < LAST_N_DAYS:' + numOfDays.toString();
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Field_Change__c> scope) {
        try {
            List<SObject> relations = new List<SObject>();
            String deleteQuery;
            for (Field_Change_Relation_Tracking__mdt metadata : FieldChangeRelationMetadataUtility.RELATION_METADATA_MAP.values()) {
                relations.addAll(Database.query(deleteQuery = 'SELECT Id FROM ' + metadata.Relation_Object_Name__c + ' WHERE Field_Change__c IN :scope'));
            }
            Database.delete(relations, false);
            Database.delete(scope, false);
        } catch(Exception e) {
            NebulaLoggerWrapper.log(
                NebulaLoggerWrapper.Method.RUN_EXCEPTION,
                'Exception in apex class: FieldChangePruningBatch.execute',
                NebulaLoggerWrapper.DataType.TYPE_EXCEPTION,
                e
            );
        }
    }

    public void finish(Database.BatchableContext bc) {}
}