force-app/main/default/objects/Field_Change__c/Field_Change__c.object-meta.xml
<CustomObject>
    <label>Field Change</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Field Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change__c/fields/Changed_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Changed_Record_Id__c</fullName>
    <label>Changed Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Change__c/fields/Date_Changed__c.field-meta.xml
<CustomField>
    <fullName>Date_Changed__c</fullName>
    <label>Date Changed</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Field_Change__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Field_Change_Fields</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Change__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Field_Change_Objects</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Change_Tracking_Event__e/Field_Change_Tracking_Event__e.object-meta.xml
<CustomObject>
    <label>Field Change Tracking Event</label>
    <pluralLabel>Field Change Tracking Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Change_Tracking_Event__e/fields/Date_Changed__c.field-meta.xml
<CustomField>
    <fullName>Date_Changed__c</fullName>
    <label>Date Changed</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Field_Change_Tracking_Event__e/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalvaluesets/Field_Change_Fields.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AccountId</fullName>
    </customValue>
    <customValue>
        <fullName>AccountNumber</fullName>
    </customValue>
    <customValue>
        <fullName>OwnerId</fullName>
    </customValue>
    <customValue>
        <fullName>Salutation</fullName>
    </customValue>
    <customValue>
        <fullName>FirstName</fullName>
    </customValue>
    <customValue>
        <fullName>LastName</fullName>
    </customValue>
    <customValue>
        <fullName>Name</fullName>
    </customValue>
    <masterLabel>Field Change Fields</masterLabel>
</GlobalValueSet>

force-app/main/default/globalvaluesets/Field_Change_Objects.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <masterLabel>Field Change Objects</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FieldChangeEventTriggerHandler.cls
public class FieldChangeEventTriggerHandler extends TriggerHandler {
    
    public override void afterInsert() {
        try {
            if (Test.isRunningTest() && TestUtility.THROW_TESTING_EXCEPTION) {
                throw new TestUtility.GenericTestingException();
            }
            List<Field_Change__c> fieldChanges = new List<Field_Change__c>();
            // loop through events and create field change records
            for(Field_Change_Tracking_Event__e fieldChangeEvent : (List<Field_Change_Tracking_Event__e>)Trigger.new) {
                fieldChanges.add(new Field_Change__c(
                    Changed_Record_Id__c = fieldChangeEvent.Record_Id__c,
                    Date_Changed__c = fieldChangeEvent.Date_Changed__c,
                    Field_Name__c = fieldChangeEvent.Field_Name__c,
                    New_Value__c = fieldChangeEvent.New_Value__c,
                    Object_Name__c = fieldChangeEvent.Object_Name__c,
                    Old_Value__c = fieldChangeEvent.Old_Value__c
                ));
            }
            List<Database.SaveResult> results = Database.insert(fieldChanges, false);
            // check for issues saving the Field Change records and log any errors
            for (Database.SaveResult sr : results) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        String errorString = 'Error inserting sObjects of type: Field_Change__c, ' + err.getStatusCode() + ': ' + err.getMessage();
                        if (!Test.isRunningTest()) {
                            Logger.info('Relevant records', fieldChanges);
                            Logger.error(errorString, sr);
                        } else {
                            throw new TestUtility.FailedTestingException(errorString);
                        }
                    }
                }
            }
            // Create relation records
            List<SObject> relations = new List<SObject>();
            for (Field_Change__c fieldChange : fieldChanges) {
                if (Test.isRunningTest()) {
                    relations.add(FieldChangeRelationUtility.createFieldChangeRelation(
                        FieldChangeTestUtility.DEFAULT_RELATION_OBJECT_NAME,
                        fieldChange.Id,
                        FieldChangeTestUtility.DEFAULT_RELATION_FIELD_NAME,
                        fieldChange.Changed_Record_Id__c
                    ));
                } else {
                    relations.add(FieldChangeRelationUtility.createFieldChangeRelation(
                        FieldChangeRelationUtility.RELATION_METADATA_MAP.get(fieldChange.Object_Name__c).Relation_Object_Name__c,
                        fieldChange.Id,
                        FieldChangeRelationUtility.RELATION_METADATA_MAP.get(fieldChange.Object_Name__c).Changed_Object_Lookup_Field_Name__c,
                        fieldChange.Changed_Record_Id__c
                    ));
                }
            }
            results = Database.insert(relations, false);
            // check for issues saving the Field Change Relation records and log any errors
            for (Database.SaveResult sr : results) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        String errorString = 'Error inserting sObjects of type: Field_Change_*_Relation__c, ' + err.getStatusCode() + ': ' + err.getMessage();
                        if (!Test.isRunningTest()) {
                            Logger.error(errorString, sr);
                        } else {
                            throw new TestUtility.FailedTestingException(errorString);
                        }
                    }
                }
            }
            if (!Test.isRunningTest()) {
                Logger.resumeSaving();
                Logger.saveLog();
            }
        } catch(Exception e) {
            if (!Test.isRunningTest()) {
                Logger.exception('Exception in apex class: FieldChangeEventTriggerHandler', e);
            } else {
                throw e;
            }
        }
    }
}