force-app/main/default/objects/Field_Change__c/Field_Change__c.object-meta.xml
<CustomObject>
    <label>Field Change</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Field Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/Field_Change_Relation_Tracking__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to store the API names of the various Field Change Tracking Relation objects</description>
    <label>Field Change Relation Tracking</label>
    <pluralLabel>Field Change Relation Tracking</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Changed_Object_Lookup_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Changed_Object_Lookup_Field_Name__c</fullName>
    <label>Relation Lookup Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Changed_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Changed_Object_Name__c</fullName>
    <label>Relation Lookup Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Relation_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Relation_Object_Name__c</fullName>
    <label>Relation Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FieldChangeRelationUtility.cls
public class FieldChangeRelationUtility {
    public static final Map<String,Field_Change_Relation_Tracking__mdt>  RELATION_METADATA_MAP {
        public get{
            if (RELATION_METADATA_MAP == null) {
                RELATION_METADATA_MAP = new Map<String,Field_Change_Relation_Tracking__mdt>();
                List<Field_Change_Relation_Tracking__mdt> relationObjects = [
                    SELECT
                        Changed_Object_Lookup_Field_Name__c,
                        Changed_Object_Name__c,
                        Relation_Object_Name__c
                    FROM Field_Change_Relation_Tracking__mdt
                ];
                for(Field_Change_Relation_Tracking__mdt relationObject : relationObjects) {
                    RELATION_METADATA_MAP.put(relationObject.Changed_Object_Name__c, relationObject);
                }
            }
            return RELATION_METADATA_MAP;
        }
        set;
    }

    public static SObject createFieldChangeRelation(String objectName, String fieldChangeId, String fieldName, String recordId) {
        SObject relation = Schema.getGlobalDescribe().get(objectName).newSObject();
        relation.put('Field_Change__c', fieldChangeId);
        relation.put(fieldName, recordId);
        return relation;
    }
}