force-app/main/default/objects/Field_Change_Account_Relation__c/Field_Change_Account_Relation__c.object-meta.xml
<CustomObject>
    <label>Field Change Account Relation</label>
    <nameField>
        <displayFormat>FCAR-{0000}</displayFormat>
        <label>Field Change Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Change Account Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Field Change Account Relations</relationshipLabel>
    <relationshipName>Field_Change_Account_Relations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Change_Contact_Relation__c/Field_Change_Contact_Relation__c.object-meta.xml
<CustomObject>
    <label>Field Change Contact Relation</label>
    <nameField>
        <displayFormat>FCCR-{0000}</displayFormat>
        <label>Field Change Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Change Contact Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Change_Contact_Relation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Field Change Contact Relations</relationshipLabel>
    <relationshipName>Field_Change_Contact_Relations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/Field_Change_Relation_Tracking__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to store the API names of the various Field Change Tracking Relation objects</description>
    <label>Field Change Relation Tracking</label>
    <pluralLabel>Field Change Relation Tracking</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Changed_Object_Lookup_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Changed_Object_Lookup_Field_Name__c</fullName>
    <label>Relation Lookup Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Changed_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Changed_Object_Name__c</fullName>
    <label>Relation Lookup Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field_Change_Relation_Tracking__mdt/fields/Relation_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Relation_Object_Name__c</fullName>
    <label>Relation Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field_Change_Tracking__mdt/Field_Change_Tracking__mdt.object-meta.xml
<CustomObject>
    <label>Field Change Tracking</label>
    <pluralLabel>Field Change Tracking</pluralLabel>
</CustomObject>

force-app/main/default/classes/TestMetadataFactory.cls
@isTest
public class TestMetadataFactory {
    private static final Map<String,String> FIELD_CHANGE_ACCOUNT_METADATA = new Map<String,String> {
        'Account' => 'Name',
        'Account' => 'AccountNumber'
    };
    public static final Integer TESTING_ACCOUNT_FIELD_CHANGE_METADATA_COUNT = FIELD_CHANGE_ACCOUNT_METADATA.keySet().size();
    private static final Map<String,String> FIELD_CHANGE_CONTACT_METADATA = new Map<String,String> {
        'Contact' => 'FirstName',
        'Contact' => 'LastName'
    };
    public static final Integer TESTING_CONTACT_FIELD_CHANGE_METADATA_COUNT = FIELD_CHANGE_CONTACT_METADATA.keySet().size();

    public static DataFactoryBundle createFieldChangTrackingObjects() {
        List<Field_Change_Tracking__mdt> fieldChangeObjects = new List<Field_Change_Tracking__mdt>();
        Integer i = 1;
        for (String key : FIELD_CHANGE_ACCOUNT_METADATA.keySet()) {
            fieldChangeObjects.add(new Field_Change_Tracking__mdt(
                DeveloperName = 'AccountTesting' + i,
                MasterLabel = 'AccountTesting' + i,
                Object_Name__c = key,
                Field_Name__c = FIELD_CHANGE_ACCOUNT_METADATA.get(key)
            ));
            i++;
        }
        Integer j = 1;
        for (String key : FIELD_CHANGE_CONTACT_METADATA.keySet()) {
            fieldChangeObjects.add(new Field_Change_Tracking__mdt(
                DeveloperName = 'ContactTesting' + j,
                MasterLabel = 'ContactTesting' + j,
                Object_Name__c = key,
                Field_Name__c = FIELD_CHANGE_CONTACT_METADATA.get(key)
            ));
            j++;
        }
        FieldChangeMetadataUtility.fieldChangeMetadataRecords = fieldChangeObjects;
        return new DataFactoryBundle(fieldChangeObjects);
    }

    public static DataFactoryBundle createFieldChangeTrackingRelations() {
        List<Field_Change_Relation_Tracking__mdt> fieldChangeRelations = new List<Field_Change_Relation_Tracking__mdt>{
            new Field_Change_Relation_Tracking__mdt(
                DeveloperName = 'AccountTesting',
                MasterLabel = 'AccountTesting',
                Changed_Object_Name__c = 'Account',
                Changed_Object_Lookup_Field_Name__c = 'Account__c',
                Relation_Object_Name__c = 'Field_Change_Account_Relation__c'
            ),
            new Field_Change_Relation_Tracking__mdt(
                DeveloperName = 'ContactTesting',
                MasterLabel = 'ContactTesting',
                Changed_Object_Name__c = 'Contact',
                Changed_Object_Lookup_Field_Name__c = 'Contact__c',
                Relation_Object_Name__c = 'Field_Change_Contact_Relation__c'
            )
        };
        FieldChangeRelationMetadataUtility.fieldChangeRelationMetadataRecords = fieldChangeRelations;
        return new DataFactoryBundle(fieldChangeRelations);
    }

    public static DataFactoryBundle createFieldChangeTrackingObjectsWithRelations() {
        return new DataFactoryBundle(
            createFieldChangTrackingObjects().fieldChangeObjects,
            createFieldChangeTrackingRelations().fieldChangeRelations
        );
    }

    public class DataFactoryBundle {
        public List<Field_Change_Tracking__mdt> fieldChangeObjects;
        public List<Field_Change_Relation_Tracking__mdt> fieldChangeRelations;

        public DataFactoryBundle(
            List<Field_Change_Tracking__mdt> fieldChangeObjects
        ) {
            this.fieldChangeObjects = fieldChangeObjects;
        }

        public DataFactoryBundle(
            List<Field_Change_Relation_Tracking__mdt> fieldChangeRelations
        ) {
            this.fieldChangeRelations = FieldChangeRelations;
        }

        public DataFactoryBundle(
            List<Field_Change_Tracking__mdt> fieldChangeObjects,
            List<Field_Change_Relation_Tracking__mdt> fieldChangeRelations
        ) {
            this.fieldChangeObjects = fieldChangeObjects;
            this.fieldChangeRelations = FieldChangeRelations;
        }
    }
}